version: v1

root_dir: '/nEMG/data/sv90060'
seed: 123
n_classes: 7
data_split: 0.2

train:
  epochs: 100
  batch_size: 64
  lr: 1e-3
  lr_step: 10
  lr_decay: 0.5
  AMP: true

test:
  step: 10
  batch_size: 128
  save : true
