version: v1

root_dir: 'DATA PATH'
seed: 123
n_classes: 10
data_split: 0.2
n_folds: 1              # 1 : Full data, >2 : K-Folds
gpu_type: 'cpu'         # Options : cpu / single_gpu / multi_gpu
save_model : true

# multi gpu
n_gpus : 4              # 4
num_wokers: 16          # 16

# logging W&B
wandb:
  project: 'nEMG'

# Train Hyperparameters
train:
  epochs: 3
  batch_size: 4
  weighted_loss: true
  lr: 0.0001
  lr_step: 10
  lr_decay: 0.5
  AMP: true

# Valid Hyperparameters
valid:
  step: 1
  batch_size: 128
