project: nEMG
version: v1

root_dir: 'DATA_PATH'
seed: 123
n_classes: 10
data_split: 0.2
n_folds: 1              # 1 : Full data, >=2 : K-Folds
gpu_type: single_gpu         # Options : cpu / single_gpu / multi_gpu
save_model : true

# multi gpu
n_gpus : 1              # 1: single_gpu, >=2 : K-Folds
num_workers: 0          # single_gpu : 0, multi_gput : 16

# logging W&B
log:
  dir: './logs'
  platform: 'tensorboard' # Options: tensorboard / wandb
  interval: 10
  

# Train Hyperparameters
train:
  epochs: 3
  batch_size: 4
  weighted_loss: true
  lr: 0.0001
  lr_step: 10
  lr_decay: 0.5
  AMP: true

# Valid Hyperparameters
valid:
  step: 1
  batch_size: 128
