version: v1

root_dir: '/nEMG/data/sv90060'
seed: 123
n_classes: 7
data_split: 0.2
n_folds: 5              # 1 : Full data, >2 : K-Folds
gpu_type: 'single_gpu'  # Options : cpu / single_gpu / multi_gpu
n_gpus : 4              # 4
num_wokers: 16          # 16

wandb:
  project: nEMG

train:
  epochs: 100
  batch_size: 64
  lr: 1e-3
  lr_step: 10
  lr_decay: 0.5
  AMP: true

test:
  step: 10
  batch_size: 128
  save : true
