services:
  nginx:
    image: nginx
    container_name: monitoring_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일을 호스트에서 마운트
    ports:
      - "8081:80"  # HTTP 포트
      # - "443:443"  # HTTPS 포트 (SSL 사용 시)
    networks:
      - monitoring_backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus 설정 파일
    ports:
      - "9090:9090"
    networks:
      - monitoring_backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=bmi1!  # Grafana 관리자 비밀번호 설정
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - "3030:3000"  # 외부 접근용 포트
    networks:
      - monitoring_backend
  
  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring_backend

networks:
  monitoring_backend:
    driver: bridge
    name: monitoring_backend