global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_103'
    static_configs:
      - targets: ['node_exporter:9100']
  
  - job_name: 'node_85'
    static_configs:
      - targets: ['147.46.195.85:9100']
      
  # - job_name: "docker"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["host.docker.internal:9323"]